---
- name: Creates directory
  file:
    path: ~/nginx
    state: directory
- name: Copy config nginx
  copy:
    src: ~/test_work/roles/deploy/files/default.conf
    dest: ~/nginx/default.conf

- docker_compose:
    project_name: wordpress
    definition:
      version: '3'
      services:

        nginx:
          image: nginx:latest
          ports:
            - 80:80
          volumes:
            - ~/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ~/nginx/logs:/var/log/nginx
          restart: unless-stopped
          depends_on:
            - app
          networks:
            - frontend

        app:
          image: wordpress:latest
          ports:
            - 8080:80
          volumes:
            - ~/app:/var/www/html
          environment: # Здесь переменные можно не указывать, но придется потом вносить при установке
            WORDPRESS_DB_HOST: "{{WORDPRESS_DB_HOST}}"
            WORDPRESS_DB_USER: "{{WORDPRESS_DB_USER}}"
            WORDPRESS_DB_PASSWORD: "{{WORDPRESS_DB_PASSWORD}}"
            WORDPRESS_DB_NAME: "{{WORDPRESS_DB_NAME}}"
          restart: unless-stopped
          depends_on:
            - db
          networks:
            - frontend
            - backend

        db:
          image: mysql:latest
          volumes:
            - ~/db:/var/lib/mysql
          environment:
            MYSQL_DATABASE: "{{MYSQL_DATABASE}}"
            MYSQL_USER: "{{MYSQL_USER}}"
            MYSQL_PASSWORD: "{{MYSQL_PASSWORD}}"
            MYSQL_ROOT_PASSWORD: "{{MYSQL_ROOT_PASSWORD}}"
          restart: unless-stopped
          networks:
            - backend

      networks:
        frontend:
          driver: bridge
        backend:
          driver: bridge

      volumes:
        nginx:
        app:
        db:
